console:
    path:  /_console
    defaults: { _controller: CoreSphere\ConsoleBundle\Controller\ConsoleController::consoleAction }
    methods: [GET]

console_exec:
    path:  /_console/commands.{_format}
    defaults: { _controller: CoreSphere\ConsoleBundle\Controller\ConsoleController::execAction, _format: json }
    methods: [POST]
    requirements:
        _format: json
